Item Add 기능 구현 완료
MentalJava/simple-shopping-mall pull request #13
Opened 2024-07-29 10:16 UTC by MentalJava

Item add 기능 구현 완료했습니다.

Image picker로 gallery 사진 고른 후 Obx 사용해서 화면에 띄우기 성공

save 버튼으로
Firebase Storage > image 
Firebase database > Item name, price, description, imageUrl
저장 완료

2024-07-29 13:58 UTC, kdjun97 requested changes
코멘트 챙겨주세요. @MentalJava

2024-07-29 13:58 UTC, kdjun97 commented on lib/controller/item_controller.dart
> +  Future<void> uploadItem(String name, price, description) async {
예외 처리 굳 @MentalJava

2024-07-29 13:58 UTC, kdjun97 commented on lib/controller/item_controller.dart
> +    try {
firebase에 add할 떄, 시간이 좀 걸리는 것으로 아는데, loading 넣어줘도 좋을 것 같아요. @MentalJava 👍

2024-07-29 13:58 UTC, kdjun97 commented on lib/screens/home_add.dart
> +            onPressed: () {
await가 필요해보입니다. 혹시 의도인가요? @MentalJava

2024-07-30 07:13 UTC, MentalJava commented on lib/controller/item_controller.dart
> +  Future<void> uploadItem(String name, price, description) async {
감사합니다 ㅎㅎ @kdjun97

2024-07-30 07:13 UTC, MentalJava commented on lib/controller/item_controller.dart
> +    try {
네 알겠습니다 !! @kdjun97

2024-08-01 10:22 UTC, MentalJava commented on lib/screens/home_add.dart
> +            onPressed: () {
추가 하였습니다 ! @kdjun97

2024-08-01 10:23 UTC, MentalJava commented on lib/controller/item_controller.dart
> +    try {
로딩 구현 완료 했습니다 ! @kdjun97

2024-08-01 14:35 UTC, kdjun97 commented on lib/controller/item_controller.dart
> +    try {
@MentalJava 굳! 👍

2024-08-01 14:38 UTC, kdjun97 requested changes
코멘트 챙겨주세요. @MentalJava

2024-08-01 14:38 UTC, kdjun97 commented on lib/screens/home_add.dart
> +            onPressed: () {
@MentalJava 다시 확인해주세요

2024-08-01 14:38 UTC, kdjun97 commented on lib/screens/home_add.dart
> +                onPressed: () {
async 빠져있네요. @MentalJava 
아무리 뒤에 액션이 없더라도, Future를 사용하면 await는 꼭 넣어주세요.
만약 그게 필요없다면, 함수 정의부에서 Future를 빼주세요. @MentalJava

2024-08-01 14:40 UTC, kdjun97 requested changes
코멘트 챙겨주세요.

2024-08-01 14:40 UTC, kdjun97 commented on lib/screens/home_add.dart
> +                    onPressed: () {
async await 확인이요 @MentalJava

2024-08-01 14:42 UTC, MentalJava commented on lib/screens/home_add.dart
> +                onPressed: () {
확인 하였습니다 ! 이런 실수 조심하겠습니다 ㅎㅎ @kdjun97

2024-08-01 14:42 UTC, MentalJava commented on lib/screens/home_add.dart
> +                onPressed: () {
수정 완료

2024-08-01 14:46 UTC, kdjun97 requested changes
확인 한번만 부탁드리고, CircularProgressIndicator에 Opacity가 들어갔다면, 들어가지 않는 쪽으로 변경해주세요! @MentalJava

2024-08-01 14:46 UTC, kdjun97 commented on lib/screens/home_add.dart
> +                    child: const Center(
CircularProgressIndicator에도 Opacity 0.5가 들어갔는지 확인 부탁드려요 @MentalJava

2024-08-01 15:05 UTC, MentalJava commented on lib/screens/home_add.dart
> +                    child: const Center(
들어가진 않았지만 child로 들어가는건 좋지 않은 것 같아 Stack 으로 따로 나누었습니다 ! @kdjun97

2024-08-02 01:38 UTC, kdjun97 approved these changes
원했던 Loading Stack이 나온 것 같네요.
다른 방식으로 구현하는 방법도 많겠지만, 일단 이번 의도는 지금과 같이 짜는 거였어요.
고생하셨습니다. 얼마 due가 남지 않았으나, 조금만 더 고생합시다~ @MentalJava 👍

2024-08-02 01:38 UTC, merged