Home Item Feature 구현 완료
MentalJava/simple-shopping-mall pull request #15
Opened 2024-08-02 12:39 UTC by MentalJava

Fire Storage, Firestore Database 에 있는 items 를 가져와 (Stream getItems 함수) StreamBuilder로 
관리 할 수 있게 하였습니다 !

2024-08-02 15:11 UTC, kdjun97 requested changes
코멘트 확인 한번만 하구 댓글 남겨주세요! @MentalJava

2024-08-02 15:11 UTC, kdjun97 commented on lib/controller/item_controller.dart
> +  Stream<List<Item>> getItems() {
해당 부분은 constant로 관리하면 좋을 것 같아요.
위에서도 typo 이슈가 있었던 것 같은데, 전역적으로 관리하면 좋을 것 같습니다. @MentalJava

2024-08-02 15:11 UTC, kdjun97 commented on lib/models/item.dart
> +    return Item(
여기는 하나만 doc.id인데 doc.id를 접근하는 이유가 있을까요??
제가 잘 몰라서 doc['id']가 아닐까 생각이 들긴 해서 코멘트 남깁니다 @MentalJava

2024-08-02 15:56 UTC, MentalJava commented on lib/controller/item_controller.dart
> +  Stream<List<Item>> getItems() {
네 알겠습니다 주의하겠습니다 !! @kdjun97

2024-08-02 15:59 UTC, MentalJava commented on lib/models/item.dart
> +    return Item(
key & value 로 이루어진 데이터가 아니라,  document 자체 id 를 가져오는거라 그렇습니다 !! @kdjun97

2024-08-03 09:19 UTC, kdjun97 approved these changes

2024-08-03 09:19 UTC, merged