Detail Page 기능 구현
MentalJava/simple-shopping-mall pull request #24
Opened 2024-08-12 12:58 UTC by MentalJava

기능 구현 도중 문제점이 생겼습니다.

지금 여러가지 방법으로 진행 해보았는데, 추천 버튼을 눌렀을 때 바로 UI가 변경 되는게 아니라 나갔다 와야 반영이 됩니다.

이 부분에서 다른 방법이 있는지 같이 얘기 나누고 싶습니다.

2024-08-12 13:26 UTC, kdjun97 commented
너무 좋습니다. 
요로케 이것저것 시도해보다가 안되면 같이 얘기 나눠보는거 좋아요.
이따 디코에서 화면 공유하면서 얘기 나눠보시죠! @MentalJava

2024-08-13 23:22 UTC, kdjun97 requested changes
코멘트 확인 부탁드립니다. @MentalJava

2024-08-13 23:22 UTC, kdjun97 commented on lib/screens/home_detail.dart
> -                            color: Colors.red,
`<T>` 가 빠진 것 같습니다. @MentalJava

2024-08-13 23:22 UTC, kdjun97 commented on lib/screens/home_detail.dart
> -                            fontSize: 20,
GetBuilder예제를 찾아봤는데요, 
문법이 바뀌었을 가능성이 있긴 하지만, 
제가 예전에 flutter를 했을 때는, GetBuilder<T>가 필요했습니다.

지금 유준님의 코드에는 제너릭 코드가 없네요. Controller형태로 끼워주시면 될 것 같습니다.

아래는 예시 코드 가져온 것 입니다. @MentalJava 

GetBuilder<Controller>(
	init: Controller(), // GetBuilder안 init
	builder: (_) {
    	return Text('count : ${_.count}');
    },
),

2024-08-14 06:11 UTC, MentalJava commented on lib/screens/home_detail.dart
> -                            color: Colors.red,
확인했습니다 ! @kdjun97

2024-08-14 06:11 UTC, MentalJava commented on lib/screens/home_detail.dart
> -                            fontSize: 20,
감사합니다 적용해보고 다시 commit 올리겠습니다 ! @kdjun97

2024-08-14 11:21 UTC, kdjun97 approved these changes
이번 프로젝트도 고생하셨습니다~ @MentalJava

2024-08-14 11:21 UTC, merged