Detail Modified Feature 구현 완료
MentalJava/simple-shopping-mall pull request #26
Opened 2024-08-22 04:31 UTC by MentalJava

update 메소드로 기존 firestore database 에 있는 data 들과 storage 에 있는 image file 수정 될 수 있게

Feature 구현 완료 했습니다.

2024-08-25 00:54 UTC, kdjun97 requested changes
코멘트 확인해주세요. @MentalJava

2024-08-25 00:54 UTC, kdjun97 commented on lib/screens/detail_modified.dart
> -            onPressed: () {},
async 누락 @MentalJava

2024-08-25 11:03 UTC, MentalJava commented on lib/screens/detail_modified.dart
> -            onPressed: () {},
네 확인했습니다. @kdjun97

2024-08-26 14:14 UTC, kdjun97 approved these changes
고생하셨습니다. @MentalJava

2024-08-26 14:14 UTC, merged