DropButton UI 및 Feature 구현
MentalJava/simple-shopping-mall pull request #28
Opened 2024-08-27 14:59 UTC by MentalJava

DropButton UI 및 Feature 구현

2024-08-28 23:39 UTC, kdjun97 requested changes
코멘트 챙겨주세요 @MentalJava

2024-08-28 23:39 UTC, kdjun97 commented on lib/widgets/button/custom_dropdown_button.dart
> +class CustomDropdownButton extends StatelessWidget {
공통 위젯에 Controller를 선언하는 부분은 피해주세요.
다른 방법으로도 충분히 구현 가능해보입니다! @MentalJava

2024-08-28 23:39 UTC, kdjun97 commented on lib/screens/home_add.dart
> +                    inputFormatters: <TextInputFormatter>[
알맞은 외부 패키지를 찾아서 사용하는 것 👍 @MentalJava

2024-08-28 23:39 UTC, kdjun97 commented on lib/controller/item_controller.dart
> +    switch (dropController.currentItem.value) {
asc보다는 되도록 풀네임으로 써주시면 코드리뷰할 때 더 좋을 것 같아요. @MentalJava

2024-08-28 23:39 UTC, kdjun97 commented on lib/controller/item_controller.dart
> +        );
desc도 위와 마찬가지 @MentalJava

2024-08-28 23:39 UTC, kdjun97 commented on lib/controller/dropdown_button_controller.dart
> +
제가 Flutter 문법을 잘 몰라서 그러는데,
extension 사용을 한 이유가 따로 있을까요?? @MentalJava

2024-08-30 10:07 UTC, MentalJava commented on lib/widgets/button/custom_dropdown_button.dart
> +class CustomDropdownButton extends StatelessWidget {
네 알겠습니다 수정하겠습니다 ! @kdjun97

2024-08-30 10:07 UTC, MentalJava commented on lib/screens/home_add.dart
> +                    inputFormatters: <TextInputFormatter>[
감사합니다 ㅎㅎ @kdjun97

2024-08-30 10:07 UTC, MentalJava commented on lib/controller/item_controller.dart
> +    switch (dropController.currentItem.value) {
네 알겠습니다 ! @kdjun97

2024-09-02 14:19 UTC, MentalJava commented on lib/controller/dropdown_button_controller.dart
> +
enum 기능이 한정적이라 extension을 사용해서 확장 할 수 있습니다 ! 
근데 다시 찾아본 바로는 현재 enum 기능이 많이 추가되어 따로 확장할 필요가 없다고 하네요 ! 이점 유의해서 다음 프로젝트에 적용 하겠습니다 ㅎㅎ

2024-09-03 23:12 UTC, kdjun97 approved these changes
이번 프로젝트도 고생 많으셨습니다! @MentalJava 👍

2024-09-03 23:12 UTC, merged